parameters:
    sonata.media.admin.media.controller: AwaresoftSonataMediaBundle:MediaCRUD
    sonata.media.admin.gallery.controller: AwaresoftSonataMediaBundle:GalleryCRUD

services:
    awaresoft.media.admin.media.extension:
        class: Awaresoft\Sonata\MediaBundle\Admin\Extension\MediaAdminExtension
        tags:
            - { name: sonata.admin.extension, target: sonata.page.admin.page }

    awaresoft.media.admin.gallery.extension:
        class: Awaresoft\Sonata\MediaBundle\Admin\Extension\GalleryAdminExtension
        tags:
            - { name: sonata.admin.extension, target: sonata.media.admin.gallery }